### ISSUE TITLE
Unable to run program

### ISSUE THREAD

**Issue by zhang-GGbond** [irfanICMLL/TorchDistiller#1]
![2021-09-29 102347](https://user-images.githubusercontent.com/66502007/135192568-7c2e9604-4260-4160-bdc7-ea3ea266f9b7.png)
thanks for your excellent work
The program cannot be run after loading images and models.

**Comment by GeneralJing** [comment]
where did you get the teacher_city.pth? I got the teacher model from the "Teacher: PSPNet (ResNet-101) trained on Cityscapes " link, and rename the model name to teacher_city.pth, but is saied mismatch dims.
